server:
    port: 8085

spring:
    application:
        name: kindergarden-admin

management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-service:8761/eureka//
        healthcheck:
            enabled: true